# Generated by Django 4.2.7 on 2023-11-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoor',
            name='authorization',
            field=models.BooleanField(default=False, verbose_name='Autorização'),
        ),
    ]
