# Generated by Django 4.2.7 on 2023-11-26 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userDoor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userStudent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userSystem',
        ),
    ]
