# Generated by Django 3.0.3 on 2023-11-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoor',
            name='isUser',
            field=models.BooleanField(default=True),
        ),
    ]
