# Generated by Django 4.2.7 on 2023-11-30 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0002_remove_user_userdoor_remove_user_userstudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userform.userdoor'),
        ),
    ]
