# Generated by Django 4.2.7 on 2023-11-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0003_alter_punchcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchcard',
            name='punch_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
