# Generated by Django 4.2.7 on 2023-11-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0004_alter_punchcard_punch_in_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punchcard',
            name='out',
        ),
    ]
