# Generated by Django 4.2.7 on 2023-12-13 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alunos', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('lux', models.FloatField()),
                ('humidade', models.FloatField()),
                ('voltagem', models.FloatField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
