# Generated by Django 2.2.5 on 2023-07-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_analyst',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_coordinator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
    ]
