# Generated by Django 3.1.4 on 2023-10-14 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20231013_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_coordinator',
            field=models.ForeignKey(limit_choices_to={'user_type': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome Completo'),
        ),
    ]
