# Generated by Django 3.1.4 on 2023-10-14 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20231014_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoor',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 14, 20, 5, 51, 937473)),
            preserve_default=False,
        ),
    ]
