# Generated by Django 3.1.4 on 2023-10-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20231014_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdoor',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
