# Generated by Django 3.1.4 on 2023-10-14 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20231014_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 10, 14, 23, 5, 33, 238033)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdoor',
            name='created_by',
            field=models.CharField(default='me', max_length=100),
            preserve_default=False,
        ),
    ]
